name: Cron Job

on:
  schedule:
    - cron: '0 19,22 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies using yarn
        run: yarn install --frozen-lockfile
      - name: Start
        run: yarn start
